### ISSUE TITLE
Blog posts showing even if their date in future

### ISSUE THREAD

**Issue by HACKHERS** [rainlab/blog-plugin#364] opened 2018-02-10 20:37 UTC
Hello,

I don't think this is a bug, at least in a way blog plugin designed. But It makes scheduling impossible. Maybe we can add second option like schedule or simply change the SQL query and get posts only published before 'now'.

**Comment by LukeTowers** [comment] 2018-02-10 21:22
You are correct, this isn't a bug, it's a feature that is only enabled for logged in backend users. See https://github.com/rainlab/blog-plugin/issues/349#issuecomment-346855846.

Duplicate of #349.

**Closed by LukeTowers** 2018-02-10 21:22 UTC
