### ISSUE TITLE
Post page not using configured layout

### ISSUE THREAD

**Issue by olayrocx** [rainlab/blog-plugin#306] opened 2017-04-22 18:17 UTC
I've a little bit problem with the post layout, which is not using defined layout, but using page-all/defaultLayoutName meanwhile on backend I've set the post, postList, and postCategories to use diferent layout,  I'm using laratify octascin themes, not testing on other themes yet. This layout worked on postList and PostCategories, but not got error on post page, any idea?

**Comment by LukeTowers** [comment] 2017-04-23 01:09
I have no idea what you're asking, sorry.

**Comment by daftspunk** [comment] 2017-04-23 02:40
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by LukeTowers** [comment] 2017-10-26 22:32
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-26 22:32 UTC
Labels: Status: Revision Needed, Type: Question
