### ISSUE TITLE
Unpublished blog posts show up in plugins such as sitemap

### ISSUE THREAD

**Issue by bnordland** [rainlab/blog-plugin#271] opened 2016-12-31 03:55 UTC
If a blog post is created but not published, they show up in the sitemap. 

Steps to recreate:

1.  Install blog plugin and sitemap plugin
2. Add the type of "all blog posts" to the sitemap
3. create a blog post but do not publish it.

Result: The sitemap will contain the unpublished post, however the link will not bring up a post since the front end is smart enough to not display unpublished posts.

Expected Result: The sitemap should contain published blog posts only.

I believe the problem is in the blog post model.

**Comment by LukeTowers** [comment] 2017-05-29 19:55
Duplicate of https://github.com/rainlab/sitemap-plugin/issues/45

**Closed by LukeTowers** 2017-05-29 19:55 UTC
