### ISSUE TITLE
Blog: Post Lists Component displays unpublished posts !

### ISSUE THREAD

**Issue by ranmichael** [rainlab/blog-plugin#359] opened 2018-01-05 18:17 UTC
October Build: 431
Rainlab Blog: 1.2.19
---

Steps to reproduce:
- Create a few blog posts - leave at least one unpublished.
- Create a new CMS page
 - Add the Post List component, leave it to its default values.
i.e. Post Order: Published(Descending)
- Go to the new page's URL in the Front-End.
Notice bug - All posts are listed, even those who are not published.

Edit:
Related to #346 ?

**Comment by LukeTowers** [comment] 2018-01-05 20:40
Duplicate of #349. See https://github.com/rainlab/blog-plugin/issues/349#issuecomment-347807046.

**Closed by LukeTowers** 2018-01-05 20:40 UTC
