### ISSUE TITLE
content_html and summary translation not working

### ISSUE THREAD

**Issue by WrobelekStudio** [rainlab/blog-plugin#299] opened 2017-03-21 11:28 UTC
Translation not working when using {{ post.content_html|raw }} and {{ post.summary }}. 

I found that I can replace {{ post.content_html|raw }} with {{ post.content|md|raw }} and then translation is working. I can't find workaround for summary.

Using Small Extensions plugin, what adds WYSIWYG editor to Blog plugin. It writes content as html code (what I see after disabling Small Extensions plugin).

Blog version: 1.2.14
Octobercms version: 396

**Comment by LukeTowers** [comment] 2017-10-26 22:31
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-26 22:31 UTC

**Comment by viezel** [comment] 2018-02-02 11:52
I can confirm that this is still an issue in the current 1.2.19.
`post.content_html|raw` is not translated
`post.content|md|raw` is translated

Please reopen @LukeTowers

**Comment by LukeTowers** [comment] 2018-02-02 14:41
@viezel can you do some debugging on why that's happening?

**Comment by foxik0169** [comment] 2018-11-02 15:02
Hello,

this bug is still present in 1.2.19. In blog plugin there is logic in the beforeSave function which stores the "compiled" html in the content_html field. I expect there is a problem with the implementation when the post is saved, the translate plugin doesn't run the command for its translated field (translated content_html is empty). Don't know if this is a problem with this plugin or the translate. 

I currently used a workaround which disables the intermediate compilation of markdown as I don't think it will impact performance that much. When I find a better solution I will post it here.

**Comment by foxik0169** [comment] 2018-11-04 17:10
Hello,

so after some time spent trying to come up with a better solution I wasn't able to come up with one. The problem is that as I said before beforeSave is not called for the translated version of the field.

My solution was to update the translated fields by hand in the beforeSave function if isClassExtendedWith() was true for the TranslatableModel behavior. For this to work tho I had to create a function in the TranslatableBehaviour (base class of TranslatableModel) and add a function which exposes the knownLocales of the model to be able to iterate through them and update their value. This change was kind of a big no-no for me but I've continued just to see if this implementation could work. 

But after finalizing this function I've found another issue. The translate plugin binds to 'model.saveInternal' event which fires before beforeSave function (at least in my case?). So even when I fill the fields in the beforeSave function, the internal logic of saving translated fields has been executed before that.

So I think my conclusion is that this problem doesn't have a quick solution and would have to be implemented somehow in translate plugin via some sort of event that would enable the model to provide computed fields.

**Comment by LukeTowers** [comment] 2018-11-05 15:16
@WrobelekStudio I'm open to any suggestions as long as you can clearly explain how it works & why it's necessary :)

**Comment by bennothommo** [comment] 2019-07-23 16:18
Fixed by https://github.com/rainlab/translate-plugin/pull/419.

**Comment by mmorells** [comment] 2019-09-27 13:59
Still having this issue in version 1.6.2

**Comment by LukeTowers** [comment] 2019-09-27 19:25
@bennothommo That PR added the event, but did this plugin ever actually make use of it to fix the reported issue?
