### ISSUE TITLE
Support Unicode character slug format

### ISSUE THREAD

**Issue by baram204** [rainlab/blog-plugin#186] opened 2016-02-27 16:16 UTC
![_013](https://cloud.githubusercontent.com/assets/11155414/13373779/203ad646-ddb4-11e5-9bbb-4b5803c74c43.png)

In laravel I commnet out 

https://github.com/illuminate/support/blob/master/Str.php 350 lines

```
public static function slug($title, $separator = '-')
{
    $title = static::ascii($title);
```

but still invalid slug format error.

What do i do?

What code do i comment out??

**Comment by LukeTowers** [comment] 2017-02-10 01:10
Related: https://github.com/octobercms/library/pull/178
Duplicate of https://github.com/rainlab/blog-plugin/issues/17

**Closed by LukeTowers** 2017-02-10 01:10 UTC
Labels: duplicate
