### ISSUE TITLE
Error after upgrading to latest version: "Maximum function nesting level of '1000' reached, aborting!"

### ISSUE THREAD

**Issue by Calinou** [rainlab/blog-plugin#523] opened 2020-10-09 18:35 UTC
**PHP version:** 7.4.11
**October version:** 1.1.0
**Rainlab blog plugin version:** 1.4.3

After updating the Rainlab blog plugin from an old ~2017 version on a site with no posts, I get the following error when loading any page not part of the backend:

![image](https://user-images.githubusercontent.com/180032/95619491-01a26680-0a6f-11eb-8d33-be4e041cf213.png)

(The full stack trace is much longer but it's mostly the same thing repeating over and over.)

Running `php artisan plugin:refresh rainlab.blog` didn't resolve the issue.

The theme's source code is at [godotengine/godot-website](https://github.com/godotengine/godot-website).

**Comment by bennothommo** [comment] 2020-10-13 08:35
@Calinou if possible, are you able to provide the full backtrace (perhaps as a download if it's too huge)? I'm just trying to determine which method or function within the Blog plugin kicks off the loop?

**Comment by Calinou** [comment] 2020-10-13 12:00
@bennothommo Here's the saved HTML page: [Exception.zip](https://github.com/rainlab/blog-plugin/files/5371121/Exception.zip)

**Comment by Calinou** [comment] 2020-10-13 17:53
@LukeTowers Here's the theme: [godotengine.zip](https://github.com/rainlab/blog-plugin/files/5373167/godotengine.zip)

**Comment by Calinou** [comment] 2020-10-14 13:44
@LukeTowers Here's the database dump from development after upgrading October and plugins: [october.sql.zip](https://github.com/rainlab/blog-plugin/files/5378548/october.sql.zip)

PS: I noticed that an individual blog article like `http://localhost:8000/article/first-blog-post` will load successfully.

**Comment by daftspunk** [comment] 2021-04-05 04:54
This is almost certainly caused by some recursion found within your theme. If you still require professional assistance with this, we can assist with our [premium support programme](https://octobercms.com/premium-support).

Closing since it has been a while, hope you got it sorted. Thanks

**Closed by daftspunk** 2021-04-05 04:54 UTC
Labels: Priority: High, Status: Response Needed, Type: Unconfirmed Bug
