### ISSUE TITLE
SQL Exception on Postgres

### ISSUE THREAD

**Issue by rosuji-mms** [rainlab/blog-plugin#176] opened 2016-01-21 17:07 UTC
I am getting this SQL exception. I am a bit lost as to the issue. 

SQLSTATE[42803]: Grouping error: 7 ERROR: column "rainlab_blog_categories.nest_left" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...s"."post_id" = "rainlab_blog_posts"."id" order by "nest_left... ^ (SQL: select "rainlab_blog_posts".*, (select string_agg(name::VARCHAR, ', ') from "rainlab_blog_categories" inner join "rainlab_blog_posts_categories" on "rainlab_blog_categories"."id" = "rainlab_blog_posts_categories"."category_id" where "rainlab_blog_posts_categories"."post_id" = "rainlab_blog_posts"."id" order by "nest_left" asc) as "categories" from "rainlab_blog_posts" order by "published_at" desc limit 25 offset 0)

**Comment by rosuji-mms** [comment] 2016-01-21 17:35
The issue seems to stem from the trait -> use \October\Rain\Database\Traits\NestedTree;

**Comment by rosuji-mms** [comment] 2016-01-21 17:39
Investigation further -> NestedTreeScope -> apply function -> $builder->orderBy($model->getLeftColumnName()); seems to be the root of the issue

**Comment by daftspunk** [comment] 2016-01-22 05:19
Duplicate of #171

**Comment by LukeTowers** [comment] 2017-02-10 01:07
#171 was fixed, closing this.

**Closed by LukeTowers** 2017-02-10 01:07 UTC
