### ISSUE TITLE
Post Only Displays & Outputs First Paragraph When Using WYSIWYG Editor (Pictures)

### ISSUE THREAD

**Issue by flip4bytes** [rainlab/blog-plugin#76] opened 2015-04-15 00:32 UTC
I was so happy to see that this blog now works with the WYSIWYG editor. Makes my life so much easier when dealing with clients adding content.

I thought I was going crazy though, it was a bit odd at first here as it doesn't mirror the content on the left, it only accounts for the first paragraph, but I figured it was just a visual bug:

![Wrong Output](https://s3.amazonaws.com/f.cl.ly/items/3P1A2Q1m1B2v3t0X3A2G/Image%202015-04-14%20at%208.23.43%20PM.png)

Low and behold, the actual saved output using the default `{{ post.content_html|raw }}` on the blog turned out to be only the first paragraph too. Same amount that was displayed in the editor's live preview:

![Output content is messed up](https://s3.amazonaws.com/f.cl.ly/items/3a1T380N3z1y3v3I2G2H/Image%202015-04-14%20at%208.27.44%20PM.png)

The only way to fix it on my end is by turning off the WYSIWYG editor and then the content begins to mirror on the right-hand side and outputs properly. Only problem is that I need the WYSIWYG editor for my clients to manage their blog posts.

Thanks!

**Comment by justanne** [comment] 2015-04-18 06:28
Same problem here, however, had a workaround for this at the moment.

Instead of using `{{ post.content_html | raw }}` I used `{{ post.content | raw }}` and enclosed it within a conditional tag post:
```
{% if post %}
    <h2>{{ post.title }}</h2>

    {{ post.content | raw }}

    {% if post.featured_images.count %}
    <div class="featured-images">
        <div class="row">
            {% for image in post.featured_images %}
            <div class="image">
                <a href="{{ image.path }}" data-caption="{% if image.title %}<h3>{{ image.title }}</h3>{% endif %}<p>{{ image.description }}</p>">
                    <img
                        data-src="{{ image.filename }}"
                        src="{{ image.path }}"
                        class="img-rounded"
                        alt="{{ image.description }}" />
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    
{% else %}
    <h2>Post not found</h2>
{% endif %}
```
For displaying images, as seen above, was from here: https://github.com/rainlab/blog-plugin/issues/57

As you notice the preview window still doesn't update with the content, but when you access the post page it works as usual.

Hope this helps, as we wait for the proper fix for this.

**Comment by flip4bytes** [comment] 2015-04-18 11:58
@justanne appreciate the suggestion. I will implement this for the time being, though it does cause some pretty annoying layout problems.

e.g. it adds a completely unnecessary `<p><br></p>` tag at the end of the article (even though it is not at all present in the back-end blog article even when looking at the pure html), which adds a lot of bank padding/margin at the bottom of my post. I could of course use some CSS to go and hide all of it and get rid of the br and everything, but again, like you said, it's just a quick temporary fix until it is properly resolved. So thank you for the suggestion!

Hopefully @daftspunk sees this issue eventually. I assume it probably isn't too crazy of a fix, though I could be wrong. Dealing with WYSIWYG editor output is never fun as opposed to just raw + markdown. Though unfortunately clients never want to learn markdown :stuck_out_tongue_winking_eye:

**Comment by beemankg** [comment] 2015-05-20 17:58
This is really a problem and even though i love october very much, i have troubles with users who are going to interact with the website, so, i decide to postpone usage of october untill the problem is fixed!

**Comment by flip4bytes** [comment] 2015-05-20 18:42
@beemankg yeah, I just pushed a site live today for a client and I'm really nervous about this now. Hopefully this issue is seen and remedied in the near future.

**Comment by beemankg** [comment] 2015-05-20 18:45
@flip4bytes Hopefully! I have two clients waiting for the results! And i just figure that out, that the editors suck :))) so, i gotta use another cms for them i guess, and will wait for the fixed bug in this thing!  Thanks for the post though!

**Comment by daftspunk** [comment] 2015-05-21 09:24
This issue relates to a third party plugin? Please log this fault with the author of the "WYSIWYG Editor" plugin.

As a side note, we should be adding WYSIWYG natively in a few days.

**Closed by daftspunk** 2015-05-21 09:24 UTC
