### ISSUE TITLE
This is an issue I am getting after fresh installation and trying to create a post.

### ISSUE THREAD

**Issue by thesigae** [rainlab/blog-plugin#399] opened 2018-08-09 19:25 UTC
![image](https://user-images.githubusercontent.com/20378254/43920993-4fa6ecf4-9bcf-11e8-8d1c-bc4999679922.png)
It says there is no seo-title column.

**Comment by LukeTowers** [comment] 2018-08-09 20:30
Duplicate of #398. This is from a plugin that is poorly made and interfering with this plugin.

**Closed by LukeTowers** 2018-08-09 20:30 UTC

**Comment by thesigae** [comment] 2018-08-09 20:38
I apologize I actually ended up fixed this issue. The AnandPatel seo extension has to be installed after the supported plugins are installed. Thanks @LukeTowers
