### ISSUE TITLE
Avoid published_at auto update on post save

### ISSUE THREAD

**Issue by marcomessa** [rainlab/blog-plugin#449] opened 2019-06-06 10:20 UTC
I don't know if this is a bug or a feature, but every time I edit a post, it updates its published_at field, like the updated_at one. This is happening both when edits are done in the backend and when I save the post via $model->save().

If this is the correct behavior, can you help me to find where this is happening in the plugin, in order to try to stop it?

Thank you very much!

EDIT 

I tried to hook in beforeSave event, and setting ``$model->published_at = false``, but then I receive an "Invalid datetime format" on save. I think this is related to date mutuation of the attribute, defined in the model

**Comment by w20k** [comment] 2019-06-06 12:01
@marcomessa `published_at` is added to a $dates array, so, I guess, it's by design. 

https://github.com/rainlab/blog-plugin/blob/720a1818f6c65b64dadb669c9331641397ecd0fb/models/Post.php#L61
Docs info (https://laravel.com/docs/5.8/eloquent-mutators#date-mutators)

**Comment by marcomessa** [comment] 2019-06-06 12:09
Yep, I noticed that. What I can't understand is why on each update of a Post, the value changes to current timestamp: is this a common behavior when an attribute is mutated as date?

**Comment by w20k** [comment] 2019-06-06 12:32
@marcomessa  could you paste your build & plugin version? And what do you have in your `manage` tab for a specific post?

![Screenshot 2019-06-06 at 15 31 02](https://user-images.githubusercontent.com/1053320/59032944-20d42700-8870-11e9-9bd1-376f2e278583.png)

**Comment by marcomessa** [comment] 2019-06-06 12:38
@w20k sure!
Core build: 455
Blog version: 1.3.1

<img width="1271" alt="Schermata 2019-06-06 alle 14 36 43" src="https://user-images.githubusercontent.com/4236142/59033273-9b00ad80-8868-11e9-96a3-1ddacde4b5d2.png">

The post is published. If I change somenthing (content, excerpt ecc ecc), the published_at is update with a new timestamp

**Comment by w20k** [comment] 2019-06-06 12:46
@marcomessa That's strange I've local build set to 456 and blog to 1.3.2. And I don't feel like I can reproduce your issue.
Do you have your published flag set to true as well in DB? (just a hunch)

**Comment by marcomessa** [comment] 2019-06-06 12:58
@w20k you point me to the right way. I tried a fresh plugin install and the issue is not present. In past days I extended Post model, adding two custom fields and a one to one relation. I then disabled that edits, but surely something went wrong there. I'll try to re-extend step by step untile the issue will appear (let's hope not :) )
Thank you for your support!

**Comment by w20k** [comment] 2019-06-06 13:11
@marcomessa that's awesome! Will be closing this one then!

**Closed by w20k** 2019-06-06 13:11 UTC
Labels: Type: Question
