### ISSUE TITLE
Unpublished Posts are present in the sitemap

### ISSUE THREAD

**Issue by pvullioud** [rainlab/blog-plugin#317] opened 2017-05-29 15:09 UTC
Combined with https://github.com/rainlab/sitemap-plugin
the site map return all the posts include the unpublished one.

# To reproduce the issue
- create a post in the blog without published it
- load the sitemap : https://inetis.ch/sitemap.xml
- unpublished article is present

**Comment by pvullioud** [comment] 2017-05-29 15:12
sorry duplicate with #272

**Comment by LukeTowers** [comment] 2017-05-29 19:55
Duplicate of https://github.com/rainlab/sitemap-plugin/issues/45

**Closed** 2017-05-29 19:54 UTC
Labels: duplicate, third party
