### ISSUE TITLE
Issue with the function gt() on a newly setup forum.

### ISSUE THREAD

**Issue by Cleanse** [rainlab/blog-plugin#237] opened 2016-09-03 21:56 UTC
```
Call to a member function gt() on null
/var/www/html/plugins/rainlab/forum/classes/TopicTracker.php line 106
```

```
$newPosts = $firstTopic->last_post_at->gt($lastLogin) &&
```

Did I perhaps misconfigure something or is this a new issue on new installs? I only get this issue when logged in.

**Comment by daftspunk** [comment] 2016-09-03 22:10
Looks like this is posted in the wrong repo. It relates to the forum plugin.

Duplicate of https://github.com/rainlab/forum-plugin/issues/95

**Closed by daftspunk** 2016-09-03 22:10 UTC
