### ISSUE TITLE
Post Expiry Date

### ISSUE THREAD

**Issue by nathanjdunn** [rainlab/blog-plugin#152] opened 2015-11-16 12:11 UTC
Hi,

Would it be possible to add a post expiry date/time to the post menu? I think a lot of users would find this useful as it means they do not have to remember to unpublish posts when they are no longer relevant.

Thanks,
Nathan

**Comment by WWRFresource** [comment] 2017-08-15 14:11
Think this is similar to #312 ?

**Comment by LukeTowers** [comment] 2017-08-15 14:15
Duplicate of #312, more conversation there so closing this.

**Closed by LukeTowers** 2017-08-15 14:15 UTC
Labels: Type: Conceptual Enhancement
