### ISSUE TITLE
Blog translate issue (just the title is translated)

### ISSUE THREAD

**Issue by norbitoth** [rainlab/blog-plugin#236] opened 2016-08-25 09:01 UTC
Hi,

When I make entry in blog in different language, then just the title is shown on the selected language, but the content_html and the excerpt is still on the original language.
When I dumped the return value from the translation module, it was ok, but on the page the content is on default language.

Thanks,
Norbert

**Comment by norbitoth** [comment] 2016-08-30 14:51
Hi,

I have tried to find a solution to the problem in the last few days and I think there is an other issue with the plugin.
When I create a blog entry and do not create the translation, then the target language shows the entry on original language. Example: I have two languages: EN and DE. My default language is EN.
The first issue is the blog doesn't save the DE entry, if I have no EN entry. Every time I have to create a fake entry on default language!!! :(
The second issue: I create EN entries and make some DE translations but not for all entries. In this case when I open blog list in DE, then I get all entries both in EN and DE. For me this is totally useless!!!
Maybe I have done something wrong. Please help in this issue!

Thanks,
Norbert

**Comment by daftspunk** [comment] 2016-09-03 01:04
Duplicate of #234

**Closed by daftspunk** 2016-09-03 01:04 UTC
